import { InjectionToken } from '@angular/core'

export type Country = {
  name: string
  telCode: string
  telPattern: string
}

export const COUNTRIES = new InjectionToken(
  'tel codes and patterns for different countries.',
  {
    factory: (): Country[] => [
      { name: 'Afghanistan', telCode: '93', telPattern: '--- --- ---' },
      { name: 'Albania', telCode: '355', telPattern: '-- --- ----' },
      { name: 'Algeria', telCode: '213', telPattern: '--- -- -- --' },
      { name: 'American Samoa', telCode: '1684', telPattern: '--- ----' },
      { name: 'Andorra', telCode: '376', telPattern: '-- -- --' },
      { name: 'Angola', telCode: '244', telPattern: '--- --- ---' },
      { name: 'Anguilla', telCode: '1264', telPattern: '--- ----' },
      { name: 'Antigua & Barbuda', telCode: '1268', telPattern: '--- ----' },
      { name: 'Armenia', telCode: '374', telPattern: '-- --- ---' },
      { name: 'Aruba', telCode: '297', telPattern: '--- ----' },
      { name: 'Ascension', telCode: '247', telPattern: '-- ---' },
      { name: 'Australia', telCode: '61', telPattern: '--- --- ---' },
      { name: 'Australian External Territories', telCode: '672', telPattern: '--- --- ---' },
      { name: 'Azerbaijan', telCode: '994', telPattern: '-- --- -- --' },
      { name: 'Bahamas', telCode: '1242', telPattern: '--- ----' },
      { name: 'Bahrain', telCode: '973', telPattern: '---- ----' },
      { name: 'Barbados', telCode: '1246', telPattern: '--- ----' },
      { name: 'Barbuda', telCode: '1268', telPattern: '--- ----' },
      { name: 'Belarus', telCode: '375', telPattern: '-- --- ----' },
      { name: 'Belgium', telCode: '32', telPattern: '--- -- -- --' },
      { name: 'Benin', telCode: '229', telPattern: '-- --- ---' },
      { name: 'Bermuda', telCode: '1441', telPattern: '--- ----' },
      { name: 'Bolivia', telCode: '591', telPattern: '- --- ----' },
      { name: 'Botswana', telCode: '267', telPattern: '-- --- ---' },
      { name: 'Brazil', telCode: '55', telPattern: '-- ----- ----' },
      { name: 'British Indian Ocean Territory', telCode: '246', telPattern: '--- ----' },
      { name: 'British Virgin Islands', telCode: '1284', telPattern: '--- ----' },
      { name: 'Brunei', telCode: '673', telPattern: '--- ----' },
      { name: 'Burkina Faso', telCode: '226', telPattern: '-- -- -- --' },
      { name: 'Burundi', telCode: '257', telPattern: '-- -- ----' },
      { name: 'Cameroon', telCode: '237', telPattern: '---- ----' },
      { name: 'Canada', telCode: '1', telPattern: '--- --- ----' },
      { name: 'Cape Verde', telCode: '238', telPattern: '--- ----' },
      { name: 'Cayman Islands', telCode: '1345', telPattern: '--- ----' },
      { name: 'Central African Republic', telCode: '236', telPattern: '-- -- -- --' },
      { name: 'Chad', telCode: '235', telPattern: '-- -- -- --' },
      { name: 'Chile', telCode: '56', telPattern: '- ---- ----' },
      { name: 'China', telCode: '86', telPattern: '--- ---- ----' },
      { name: 'Colombia', telCode: '57', telPattern: '--- --- ----' },
      { name: 'Comoros', telCode: '269', telPattern: '--- ----' },
      { name: 'Congo - Brazzaville', telCode: '242', telPattern: '-- --- ----' },
      { name: 'Congo - Kinshasa', telCode: '243', telPattern: '-- --- ----' },
      { name: 'Cote d’Ivoire', telCode: '225', telPattern: '-- --- ---' },
      { name: 'Cuba', telCode: '53', telPattern: '---- ----' },
      { name: 'Cyprus', telCode: '357', telPattern: '---- ----' },
      { name: 'Denmark', telCode: '45', telPattern: '---- ----' },
      { name: 'Djibouti', telCode: '253', telPattern: '-- -- -- --' },
      { name: 'Dominica', telCode: '1767', telPattern: '--- ----' },
      { name: 'Dominican Republic', telCode: '1 809', telPattern: '--- ----' },
      { name: 'Egypt', telCode: '20', telPattern: '-- --- ----' },
      { name: 'El Salvador', telCode: '503', telPattern: '---- ----' },
      { name: 'Equatorial Guinea', telCode: '240', telPattern: '--- --- ---' },
      { name: 'Eritrea', telCode: '291', telPattern: '- --- ---' },
      { name: 'Ethiopia', telCode: '251', telPattern: '-- --- ----' },
      { name: 'Faroe Islands', telCode: '298', telPattern: '--- ---' },
      { name: 'France', telCode: '33', telPattern: '- -- -- -- --' },
      { name: 'Gabon', telCode: '241', telPattern: '- -- -- --' },
      { name: 'Gambia', telCode: '220', telPattern: '--- ----' },
      { name: 'Germany', telCode: '49', telPattern: '--- --------' },
      { name: 'Gibraltar', telCode: '350', telPattern: '---- ----' },
      { name: 'Greece', telCode: '30', telPattern: '-- ---- ----' },
      { name: 'Greenland', telCode: '299', telPattern: '--- ---' },
      { name: 'Grenada', telCode: '1473', telPattern: '--- ----' },
      { name: 'Guam', telCode: '1671', telPattern: '--- ----' },
      { name: 'Guatemala', telCode: '502', telPattern: '- --- ----' },
      { name: 'Guinea', telCode: '224', telPattern: '--- --- ---' },
      { name: 'Guinea-Bissau', telCode: '245', telPattern: '--- ----' },
      { name: 'Honduras', telCode: '504', telPattern: '---- ----' },
      { name: 'Hungary', telCode: '36', telPattern: '-- --- ----' },
      { name: 'Iceland', telCode: '354', telPattern: '--- ----' },
      { name: 'India', telCode: '91', telPattern: '----- -----' },
      { name: 'Iran', telCode: '98', telPattern: '--- --- ----' },
      { name: 'Iraq', telCode: '964', telPattern: '--- --- ----' },
      { name: 'Ireland', telCode: '353', telPattern: '-- --- ----' },
      { name: 'Israel', telCode: '972', telPattern: '-- --- ----' },
      { name: 'Italy', telCode: '39', telPattern: '--- --- ----' },
      { name: 'Jamaica', telCode: '1876', telPattern: '--- ----' },
      { name: 'Japan', telCode: '81', telPattern: '-- ---- ----' },
      { name: 'Jordan', telCode: '962', telPattern: '- ---- ----' },
      { name: 'Kazakhstan', telCode: '77', telPattern: '--- --- -- --' },
      { name: 'Kenya', telCode: '254', telPattern: '--- --- ---' },
      { name: 'Kosovo', telCode: '383', telPattern: '---- ----' },
      { name: 'Kuwait', telCode: '965', telPattern: '---- ----' },
      { name: 'Latvia', telCode: '371', telPattern: '--- -----' },
      { name: 'Lesotho', telCode: '266', telPattern: '-- --- ---' },
      { name: 'Libya', telCode: '218', telPattern: '-- --- ----' },
      { name: 'Lithuania', telCode: '370', telPattern: '--- -----' },
      { name: 'Madagascar', telCode: '261', telPattern: '-- -- --- --' },
      { name: 'Mali', telCode: '223', telPattern: '---- ----' },
      { name: 'Malta', telCode: '356', telPattern: '-- -- -- --' },
      { name: 'Mauritania', telCode: '222', telPattern: '---- ----' },
      { name: 'Moldova', telCode: '373', telPattern: '-- --- ---' },
      { name: 'Monaco', telCode: '377', telPattern: '---- ----' },
      { name: 'Montserrat', telCode: '1664', telPattern: '--- ----' },
      { name: 'Morocco', telCode: '212', telPattern: '-- --- ----' },
      { name: 'Mozambique', telCode: '258', telPattern: '-- --- ----' },
      { name: 'Namibia', telCode: '264', telPattern: '-- --- ----' },
      { name: 'Netherlands', telCode: '31', telPattern: '- -- -- -- --' },
      { name: 'Nicaragua', telCode: '505', telPattern: '---- ----' },
      { name: 'Niger', telCode: '227', telPattern: '-- -- -- --' },
      { name: 'Northern Mariana Islands', telCode: '1670', telPattern: '--- ----' },
      { name: 'Norway', telCode: '47', telPattern: '---- ----' },
      { name: 'Oman', telCode: '968', telPattern: '---- ----' },
      { name: 'Pakistan', telCode: '92', telPattern: '--- --- ----' },
      { name: 'Palestinian Territories', telCode: '970', telPattern: '--- -- ----' },
      { name: 'Panama', telCode: '507', telPattern: '---- ----' },
      { name: 'Paraguay', telCode: '595', telPattern: '--- --- ---' },
      { name: 'Peru', telCode: '51', telPattern: '--- --- ---' },
      { name: 'Philippines', telCode: '63', telPattern: '--- --- ----' },
      { name: 'Poland', telCode: '48', telPattern: '--- --- ---' },
      { name: 'Portugal', telCode: '351', telPattern: '- ---- ----' },
      { name: 'Puerto Rico', telCode: '1 787', telPattern: '--- ----' },
      { name: 'Reunion', telCode: '262', telPattern: '--- --- ---' },
      { name: 'Romania', telCode: '40', telPattern: '--- --- ---' },
      { name: 'Russia', telCode: '7', telPattern: '--- --- -- --' },
      { name: 'Rwanda', telCode: '250', telPattern: '--- --- ---' },
      { name: 'San Marino', telCode: '378', telPattern: '--- --- ----' },
      { name: 'São Tome & Principe', telCode: '239', telPattern: '-- -----' },
      { name: 'Senegal', telCode: '221', telPattern: '-- --- ----' },
      { name: 'Serbia', telCode: '381', telPattern: '-- --- ----' },
      { name: 'Seychelles', telCode: '248', telPattern: '- -- -- --' },
      { name: 'Sierra Leone', telCode: '232', telPattern: '-- --- ---' },
      { name: 'Singapore', telCode: '65', telPattern: '---- ----' },
      { name: 'Sint Maarten', telCode: '1721', telPattern: '--- ----' },
      { name: 'Somalia', telCode: '252', telPattern: '-- --- ---' },
      { name: 'South Africa', telCode: '27', telPattern: '-- --- ----' },
      { name: 'South Sudan', telCode: '211', telPattern: '-- --- ----' },
      { name: 'Spain', telCode: '34', telPattern: '--- --- ---' },
      { name: 'Sri Lanka', telCode: '94', telPattern: '-- --- ----' },
      { name: 'St. Helena', telCode: '290', telPattern: '-- ---' },
      { name: 'St. Kitts & Nevis', telCode: '1869', telPattern: '--- ----' },
      { name: 'St. Lucia', telCode: '1758', telPattern: '--- ----' },
      { name: 'St. Vincent and the Grenadines', telCode: '1784', telPattern: '--- ----' },
      { name: 'Sudan', telCode: '249', telPattern: '-- --- ----' },
      { name: 'Suriname', telCode: '597', telPattern: '--- ----' },
      { name: 'Swaziland', telCode: '268', telPattern: '---- ----' },
      { name: 'Sweden', telCode: '46', telPattern: '-- --- ----' },
      { name: 'Switzerland', telCode: '41', telPattern: '-- --- ----' },
      { name: 'Tanzania', telCode: '255', telPattern: '-- --- ----' },
      { name: 'Thailand', telCode: '66', telPattern: '- ---- ----' },
      { name: 'Togo', telCode: '228', telPattern: '-- --- ---' },
      { name: 'Trinidad & Tobago', telCode: '1868', telPattern: '--- ----' },
      { name: 'Tunisia', telCode: '216', telPattern: '-- --- ---' },
      { name: 'Turkey', telCode: '90', telPattern: '--- --- ----' },
      { name: 'Turkmenistan', telCode: '993', telPattern: '-- ------' },
      { name: 'Turks & Caicos Islands', telCode: '1649', telPattern: '--- ----' },
      { name: 'U.S. Virgin Islands', telCode: '1340', telPattern: '--- ----' },
      { name: 'Uganda', telCode: '256', telPattern: '-- --- ----' },
      { name: 'Ukraine', telCode: '380', telPattern: '-- --- -- --' },
      { name: 'United Arab Emirates', telCode: '971', telPattern: '-- --- ----' },
      { name: 'United Kingdom', telCode: '44', telPattern: '---- ------' },
      { name: 'United States', telCode: '1', telPattern: '--- --- ----' },
      { name: 'Uruguay', telCode: '598', telPattern: '---- ----' },
      { name: 'Uzbekistan', telCode: '998', telPattern: '-- -------' },
      { name: 'Venezuela', telCode: '58', telPattern: '--- --- ----' },
      { name: 'Yemen', telCode: '967', telPattern: '--- --- ---' },
      { name: 'Zambia', telCode: '260', telPattern: '-- --- ----' },
      { name: 'Zimbabwe', telCode: '263', telPattern: '-- --- ----' },
    ],
  }
)
